### ISSUE TITLE
Stackn logo not rendered

### ISSUE THREAD

**Issue by Wrede** [scaleoutsystems/stackn#231]
**Severity**
- [ ] Critical/Blocker
- [ ] High 
- [ ] Medium
- [x] Low

**Describe the bug**
In develop branch: base.html in ./components/studio/templates uses the Studio SaaS logo which does not exist in the repository. However, stackn.png exists but with low resolution.

**Expected behavior**
Default should be to use stackn.png as logo. 

**Additional**
Change stackn.png with a higher resolution.

**Comment by carmat88** [comment]
@Wrede When you have time, please consider closing this issue for PR #232 has now been merged. Thank you!

**Comment by Wrede** [comment]
yes thanks!
