### ISSUE TITLE
"stackn delete app" not working from CLI 

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/stackn#238]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [ ] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [x] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
When I delete apps from the CLI, they do not seem to get deleted. See screenshot. 

**Expected behavior**
For them to be deleted. 

**Screenshots**
![Uploading Skärmavbild 2021-10-19 kl. 14.53.12.png…]()

**Contact Details**
An e-mail address in case we need to contact you for further details regarding this issue.

**Comment by carmat88** [comment]
**Update**: a new PR will take care of this by a major refactoring and improving of the CLI.
