### ISSUE TITLE
Model delete 

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/stackn#31]
**Is your enhancement request related to a problem? Please describe.**
Currently it is not possible to delete models from the CLI/API since the Django API does not expose the method, see screenshot. 
![Skärmavbild 2020-03-31 kl  12 00 26](https://user-images.githubusercontent.com/2364390/78014710-9d2c7f00-7348-11ea-85ba-08f343452b53.png)

**Describe the solution you'd like**
It should be possible to delete models. But we need to discuss permissions and access control for incdividual models. Some models should be read-only, for example seed models for FedML

**Describe alternatives you've considered**

**Additional context**

**Comment by dstoyanova** [comment]
@ahellander 

It seems like the problem was caused by an authentication/authorization issue and after introducing the token authentication, the problem is resolved. An example code for removing a model could be:

```
import requests
headers = {"Content-Type": "application/json", "Authorization": "Token 	c7743921e23b3df63f97860e264c8deb8597a082"}
url = "http://34.231.147.144.nip.io/api/models/2/"
r = requests.delete(url, headers=headers)
r.text
```

which will return 'ok' and remove the object from the db.
