### ISSUE TITLE
Password change page not rendering in 0.7

### ISSUE THREAD

**Issue by akochari** [scaleoutsystems/stackn#320]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [ X ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [ ] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
The page for password change (/accounts/password_change/) not rendering. Error during template rendering
In template /app/templates/registration/password_change_form.html, error at line 5

'crispy_forms_tags' is not a registered tag library. Must be one of: admin_list admin_modify admin_urls cache can_create_app custom_tags debugger_tags get_setting guardian_tags highlighting i18n indent_text l10n log rest_framework static syntax_color tz widont

**Environment:**
 - OS: [e.g. mac OS]
 - Version: [e.g. macOS Catalina]

**Reproduction Steps**

**Expected behavior**

**Screenshots**

**Contact Details**
An e-mail address in case we need to contact you for further details regarding this issue.

**Comment by Wrede** [comment]
fixed in mentioned linked commit. Closing.
