### ISSUE TITLE
Hide or fix "Import from" from the card to start new project ? 

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/stackn#83]
Until we have implemented git-sync #33 we should hide the shortcut to import a project from github. At least it is currently not working. 

However,  even a one-off import would be a useful feature now since we could easily set up demo-project then.

**Comment by morganekmefjord** [comment]
It should be working? @dstoyanova can you take a look?

**Comment by dstoyanova** [comment]
I couldn't reproduce the issue. The import seems to be working fine so, I don't see a need for hiding the button. I'm closing the ticket and if there is a need for refactoring the import functionality, please open a new one.
