### ISSUE TITLE
Set up repo for "gitflow"

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/stackn#84]
According to our engineering guidelines. Assuming we still want to use that model. 

This will increase in importance now.

**Comment by dstoyanova** [comment]
@ahellander @morganekmefjord @stefanhellander 

We discussed this during the retrospective this morning and there were a few key points:

- we're not introducing _develop_ branch yet trying to stay as agile as possible, keeping the pull requests small and the development pace high
- we're locking the _master_ branch for direct commits and pushes, it's done only through an approved pull request
- we'll reflect on this frequently and if needed, we'll introduce the gitflow strategy on Stackn  as well

I'm closing this ticket for now and let's re-open it if needed.
