### ISSUE TITLE
Project overview card shows "None" sometimes

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/stackn#92]
See screenshot from first minute of demo. But hen it changed. 
![Skärmavbild 2020-05-13 kl  10 31 08](https://user-images.githubusercontent.com/2364390/81790181-51ebbb80-9505-11ea-91c1-f7031831f0ff.png)

**Comment by morganekmefjord** [comment]
@dstoyanova Can you investigate and fix.
