### ISSUE TITLE
I see public deployments from other projects in the Deployment view

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/stackn#97]
It feels a bit odd that we see deployments from other projects in view even though they are public. What should the behavior be here?
![Skärmavbild 2020-05-13 kl  20 38 27](https://user-images.githubusercontent.com/2364390/81855772-129e8880-9560-11ea-93b5-bbed3db38166.png)

**Comment by morganekmefjord** [comment]
Please specify better what your bug is. Are you refering to your projects/deployments view then its a bug. If you se other peoples models that are publicly available under root /deployments then it is as intended.

**Comment by ahellander** [comment]
Right. I was meaning to attach a screenshot. Yes, the issue is that I see them in projects/deployments.

**Comment by morganekmefjord** [comment]
Well than its a bug!
